# Generated by Django 4.2.6 on 2023-10-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Food',
        ),
    ]
