# Generated by Django 4.2.6 on 2023-10-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
