# Generated by Django 4.2.6 on 2023-11-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=150)),
                ('price1', models.FloatField()),
                ('discount_price1', models.FloatField()),
                ('description1', models.TextField()),
                ('image1', models.CharField(max_length=300)),
            ],
        ),
    ]
