# Generated by Django 4.2.6 on 2023-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0007_food2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('Address', models.TextField()),
                ('Address_2', models.TextField()),
                ('zip', models.PositiveIntegerField()),
                ('Name_on_card', models.CharField(max_length=100)),
                ('Credit_card_number', models.PositiveIntegerField()),
                ('Expiration', models.DateField()),
                ('CVV', models.PositiveIntegerField()),
            ],
        ),
    ]
