# Generated by Django 4.2.6 on 2023-11-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0008_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='zip',
            new_name='pincode',
        ),
    ]
