# Generated by Django 4.2.6 on 2023-11-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0009_rename_zip_pay_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='Email',
        ),
    ]
