# Generated by Django 4.2.6 on 2023-11-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0011_pay_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='quantity',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
