# Generated by Django 4.2.6 on 2023-11-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0012_pay_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='quantity',
        ),
    ]
