# Generated by Django 4.2.6 on 2023-11-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0013_remove_pay_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='title',
        ),
    ]
